package bbms;

import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brian
 */
public class GUI_NB extends javax.swing.JFrame {

    /**
     * Creates new form BBGUI
     */
    public GUI_NB() {
        initComponents();
        setJMenuBar(new GUIMenu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        DisplayTabs = new javax.swing.JTabbedPane();
        MainDisplay = new javax.swing.JPanel();
        InformationPanel = new javax.swing.JPanel();
        ClockPane = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        DateDisplay = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        TimeDisplay = new javax.swing.JLabel();
        AccelLabel = new javax.swing.JLabel();
        AccelDisplay = new javax.swing.JLabel();
        InfoPane = new javax.swing.JPanel();
        MiniMap = new javax.swing.JPanel();
        ConsolePanel = new javax.swing.JPanel();
        ConsoleScroll = new javax.swing.JScrollPane();
        GUIConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bare Bones Military Simulator");
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setResizable(false);

        DisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        javax.swing.GroupLayout MainDisplayLayout = new javax.swing.GroupLayout(MainDisplay);
        MainDisplay.setLayout(MainDisplayLayout);
        MainDisplayLayout.setHorizontalGroup(
            MainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        MainDisplayLayout.setVerticalGroup(
            MainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        DisplayTabs.addTab("Main Display", MainDisplay);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayTabs)
                .addContainerGap())
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayTabs)
                .addContainerGap())
        );

        InformationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));

        ClockPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLabel.setText("Date:");

        DateDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateDisplay.setText("11/14/1942");

        TimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeLabel.setText("Time:");

        TimeDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeDisplay.setText("8:42:00");

        AccelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccelLabel.setText("Accel:");

        AccelDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccelDisplay.setText("1x");

        javax.swing.GroupLayout ClockPaneLayout = new javax.swing.GroupLayout(ClockPane);
        ClockPane.setLayout(ClockPaneLayout);
        ClockPaneLayout.setHorizontalGroup(
            ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClockPaneLayout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateDisplay))
                    .addGroup(ClockPaneLayout.createSequentialGroup()
                        .addComponent(TimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimeDisplay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccelLabel)
                    .addComponent(AccelDisplay))
                .addGap(16, 16, 16))
        );
        ClockPaneLayout.setVerticalGroup(
            ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(DateDisplay)
                    .addComponent(AccelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLabel)
                    .addComponent(TimeDisplay)
                    .addComponent(AccelDisplay))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        InfoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Display"));

        javax.swing.GroupLayout InfoPaneLayout = new javax.swing.GroupLayout(InfoPane);
        InfoPane.setLayout(InfoPaneLayout);
        InfoPaneLayout.setHorizontalGroup(
            InfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        InfoPaneLayout.setVerticalGroup(
            InfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        MiniMap.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MiniMapLayout = new javax.swing.GroupLayout(MiniMap);
        MiniMap.setLayout(MiniMapLayout);
        MiniMapLayout.setHorizontalGroup(
            MiniMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MiniMapLayout.setVerticalGroup(
            MiniMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout InformationPanelLayout = new javax.swing.GroupLayout(InformationPanel);
        InformationPanel.setLayout(InformationPanelLayout);
        InformationPanelLayout.setHorizontalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClockPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MiniMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InformationPanelLayout.setVerticalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationPanelLayout.createSequentialGroup()
                .addComponent(ClockPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiniMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConsolePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));

        GUIConsole.setEditable(false);
        GUIConsole.setColumns(20);
        GUIConsole.setRows(5);
        ConsoleScroll.setViewportView(GUIConsole);

        javax.swing.GroupLayout ConsolePanelLayout = new javax.swing.GroupLayout(ConsolePanel);
        ConsolePanel.setLayout(ConsolePanelLayout);
        ConsolePanelLayout.setHorizontalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        ConsolePanelLayout.setVerticalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        
        }
        catch (Exception e) {
            System.err.println("ERROR: Cannot load Windows-like displays.");
            e.printStackTrace();
        }
    	
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_NB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_NB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_NB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_NB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_NB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AccelDisplay;
    private javax.swing.JLabel AccelLabel;
    private javax.swing.JPanel ClockPane;
    private javax.swing.JPanel ConsolePanel;
    private javax.swing.JScrollPane ConsoleScroll;
    private javax.swing.JLabel DateDisplay;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JTabbedPane DisplayTabs;
    private static javax.swing.JTextArea GUIConsole;
    private javax.swing.JPanel InfoPane;
    private javax.swing.JPanel InformationPanel;
    private javax.swing.JPanel MainDisplay;
    private javax.swing.JPanel MiniMap;
    private javax.swing.JLabel TimeDisplay;
    private javax.swing.JLabel TimeLabel;
    // End of variables declaration                   
    
	/**
	 * Prints output to the GUI Console output.  Automatically appends newline.
	 */
    public static void GCO(String str) {
    	GUIConsole.append(str + "\n");
    	GUIConsole.setCaretPosition(GUIConsole.getDocument().getLength());		
    }
}




